# bundle exec jekyll serve --host=0.0.0.0

title: MycilaESPConnect
description: Simple & Easy WiFi Manager with Captive Portal for ESP32
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  