# bundle exec jekyll serve --host=0.0.0.0

title: Simple & Easy WiFi Manager with Captive Portal for ESP32
description: A simplistic approach to a WiFi Manager on ESP32 MCUs. Comes with captive portal to configure modules without any hassle.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  